apiVersion: v1
kind: Service
metadata:
  name:  svc-sistema-noticias
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 80
      #nodePort: 30001
  selector: 
    app: sistema-noticias